### ISSUE TITLE
The modified sqstdrex.cpp is uploaded.

### ISSUE THREAD

**Issue by renshijun** [mingodad/squilu#3]
The modifications add lazy match in regex expressions. The following problem.

**Comment by renshijun** [comment]
local str = "- OAB/SP nº.:205844;";
local rex = regexp(@"(OAB)([^\d]{0,10})(\d[\d.]+)(.)");
local res = rex.capture(str);
foreach(i,val in res)
{
    print(format("match number[%02d] %s\n", i,str.slice(val.begin,val.end)));
}

execute ../bin/sq ttt.cc returns"

match number[00] OAB/SP nº.:205844;
match number[01] OAB
match number[02] /SP nº.:205844
match number[03] 205844
match number[04] ;

**Comment by mingodad** [comment]
I'm not sure I understand what you are trying to say.
Have you done any change to regex ?
Are you reporting a bug ?
Cheers !

**Comment by renshijun** [comment]
you can download my modified sqstdrex.cpp file to see the difference with squirrel3.

**Comment by mingodad** [comment]
Hello renshijun !
Thank you for your work !
Are you aware of this https://github.com/albertodemichelis/squirrel/issues/181 and if so your work fix it ?
Cheers !

**Comment by renshijun** [comment]
For a regrex object, the first capture returns right result but  the second capture returns wrong result. It seem not very hard to solve the problem. you can see my post in  albertodemichelis/squirrel#181.

**Comment by renshijun** [comment]
I solve the problem albertodemichelis/squirrel#181. 


In function SQBool sqstd_rex_search() reset match len to 0. add the following first.
 for(int i=0;i<exp->_nsubexpr;i++)
        exp->_matches[i].len = 0;

----------------------------------------------------------------------sss.cc begin
function formatCapture(cap) {
    if (cap == null) return "no match";
    // If there is a match, show the start and end index, and the length
    else return format("[%d,%d] (%d)", cap[0].begin, cap[0].end, cap[0].end - cap[0].begin);
}
local re = regexp("a.*?bc");


local strs = [
    "a bcd",
    "a bc bcd",
    "a b bcd",
];


foreach (fff in strs)
{
  re = regexp("a.*?bc");
  print(formatCapture(re.capture(fff)) + "\n");
}

foreach (fff in strs)
{
  print(formatCapture(re.capture(fff)) + "\n");
}
------------------------------------------------------------------------------------end 

../bin/sq sss.cc returns:
bash-5.0# ../bin/sq sss.cc
[0,4] (4)
[0,4] (4)
[0,6] (6)
[0,4] (4)
[0,4] (4)
[0,6] (6)
